[pytest]
minversion = 7.0
addopts =
    -vs
    --strict-markers
    --alluredir=allure-results
    --clean-alluredir
    --tracing=retain-on-failure
    --screenshot=only-on-failure
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning
